--- #YAML:1.0
name:                Math-Random-Cauchy
version:             0.02
abstract:            Random numbers following a Cauchy PDF
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steffen Mueller <smueller@cpan.org>
